### ISSUE TITLE
Why this lib exists?

### ISSUE THREAD

**Issue by felixsanz** [soundtrackyourbrand/graphql-custom-datetype#4]
Your example:

``` javascript
      now: {
        type: CustomGraphQLDateType,
        // Resolve fields with the custom date type to a valid Date object
        resolve: () => new Date()
      }
```

Isn't just the same doing this?

``` javascript
      now: {
        type: GraphQLString,
        // Resolve fields with the custom date type to a valid Date object
        resolve() {
          return new Date()
        }
      }
```

**Comment by cdroulers** [comment]
I'm not the author, but if I looked for this library because the output for `GraphQLString` with a date was

```
"createdAt": "Mon Apr 18 2016 14:20:04 GMT-0400 (Eastern Daylight Time)"
```

**Comment by claytonmarinho** [comment]
I solved this problem replacing the same field with moment.js in resolvers query.

```
Coordinate : {
    date(coordinate) {
      return moment(coordinate.date).format();
    }
}
```

**Comment by bhoriuchi** [comment]
@felixsanz a date and a string are not the same thing. This library is a custom scalar type that has parse and serialize functions as well as some error checking. If someone wants a field to return a date object, it should return a date object not a string representation that would then need to be converted to a date for every record in the results

this lib also serializes date objects to strings when used as an input type.

so it exists for people that want to actually use dates as a type.

**Comment by gabrielf** [comment]
@cdroulers and @bhoriuchi are right. But it is a good question, I should update the readme!
